# -*- coding: utf-8 -*-
"""ReLu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bh8vHa4fe-8q4eUxqbiRpaal5Pnpcj09
"""

import numpy as np
import matplotlib.pyplot as plt
import streamlit as st  # <--- Make sure this is at the top

x = np.linspace(-10, 10, 400)
y = np.maximum(0, x)

plt.figure()
plt.plot(x, y)
plt.xlabel("Input")
plt.ylabel("Output")
plt.title("ReLU Activation Function")

# CHANGE THIS LINE:
st.pyplot(plt.gcf())